// Code generated by ent, DO NOT EDIT.

package class

const (
	// Label holds the string label denoting the class type in the database.
	Label = "class"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// EdgeClassLecturers holds the string denoting the class_lecturers edge name in mutations.
	EdgeClassLecturers = "class_lecturers"
	// Table holds the table name of the class in the database.
	Table = "classes"
	// ClassLecturersTable is the table that holds the class_lecturers relation/edge.
	ClassLecturersTable = "class_lecturers"
	// ClassLecturersInverseTable is the table name for the ClassLecturer entity.
	// It exists in this package in order to avoid circular dependency with the "classlecturer" package.
	ClassLecturersInverseTable = "class_lecturers"
	// ClassLecturersColumn is the table column denoting the class_lecturers relation/edge.
	ClassLecturersColumn = "class_class_lecturers"
)

// Columns holds all SQL columns for class fields.
var Columns = []string{
	FieldID,
	FieldName,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
