// Code generated by ent, DO NOT EDIT.

package class

const (
	// Label holds the string label denoting the class type in the database.
	Label = "class"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// EdgeLecturers holds the string denoting the lecturers edge name in mutations.
	EdgeLecturers = "lecturers"
	// Table holds the table name of the class in the database.
	Table = "classes"
	// LecturersTable is the table that holds the lecturers relation/edge. The primary key declared below.
	LecturersTable = "class_lecturers"
	// LecturersInverseTable is the table name for the Lecturer entity.
	// It exists in this package in order to avoid circular dependency with the "lecturer" package.
	LecturersInverseTable = "lecturers"
)

// Columns holds all SQL columns for class fields.
var Columns = []string{
	FieldID,
	FieldName,
}

var (
	// LecturersPrimaryKey and LecturersColumn2 are the table columns denoting the
	// primary key for the lecturers relation (M2M).
	LecturersPrimaryKey = []string{"class_id", "lecturer_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
