// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Class is the predicate function for class builders.
type Class func(*sql.Selector)

// Lecturer is the predicate function for lecturer builders.
type Lecturer func(*sql.Selector)
