version: '3'

services:

  lecturer-service:
    build:
      context: ./../lecturer-service
      dockerfile: ./../lecturer-service/lecturer-service.dockerfile
    restart: always
    ports:
      - "8080:80"
    deploy:
      mode: replicated
      replicas: 1
      
  rabbitmq:
    image: 'rabbitmq:3.9-alpine'
    ports:
      - "5672:5672"
    deploy:
      mode: replicated
      replicas: 1
