version: "3"

services:
  message-service:
    environment:
      SENDGRID_API_KEY: "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"
    build:
      context: ./../message-service
      dockerfile: ./../message-service/message-service.dockerfile
    ports:
      - "8080:82"
    deploy:
      mode: replicated
      replicas: 1

  student_class-service:
    build:
      context: ./../student_class-service
      dockerfile: ../student_class-service/student_class-service.Dockerfile
    ports:
      - "8000:8000"
    environment:
      RABBITMQ_HOST: rabbitmq

  rabbitmq:
    image: "rabbitmq:3.9-alpine"
    ports:
      - "5672:5672"
      - "15672:15672"
    deploy:
      mode: replicated
      replicas: 1

  message-service-db:
    image: "mysql:8.0.23"
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "secret"
      MYSQL_DATABASE: "message"
      MYSQL_USER: "tester"
      MYSQL_PASSWORD: "secret"
    volumes:
      - message_mysql_data:/var/lib/mysql

  lecturer-service-db:
    image: "mysql:8.0.23"
    restart: always
    ports:
      - "3301:3306"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "secret"
      MYSQL_DATABASE: "lecturer"
      MYSQL_USER: "tester"
      MYSQL_PASSWORD: "secret"
    volumes:
      - lecturer_mysql_data:/var/lib/mysql

networks:
  default:

volumes:
  message_mysql_data:
  lecturer_mysql_data:
