version: "3"

services:
  lecturer-service:
    image: broodjebapao/lecturer-service:1.0.0
    ports:
      - "8080:80"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      lECTURER_DATABASE_TYPE: "mysql"
      LECTURER_MYSQL_CONNECTION_STRING: "tester:secret@tcp(10.0.1.37:3306)/lecturer?parseTime=True"
      AMQP_SERVER_URL: "amqp://guest:guest@rabbitmq:5672/"

  student_class-service:
    image: broodjebapao/student_class-service:1.0.0
    ports:
      - "8000:81"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      AMQP_SERVER_URL: "amqp://guest:guest@rabbitmq:5672/"

  message-service:
    image: broodjebapao/message-service:1.0.0
    ports:
      - "8181:82"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      AMQP_SERVER_URL: "amqp://guest:guest@rabbitmq:5672/"
      SENDGRID_API_KEY: "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"

  message-service-db:
    image: "mysql:8.0.23"
    ports:
      - "3306:3306"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "secret"
      MYSQL_DATABASE: "message"
      MYSQL_USER: "tester"
      MYSQL_PASSWORD: "secret"
    volumes:
      - message_mysql_data:/var/lib/mysql

  lecturer-service-db:
    image: "mysql:8.0.23"
    ports:
      - "3307:3306"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "secret"
      MYSQL_USER: "tester"
      MYSQL_PASSWORD: "secret"
    volumes:
      - lecturer_mysql_data:/var/lib/mysql

  rabbitmq:
    image: "rabbitmq:3.9-alpine"
    deploy:
      mode: global

volumes:
  message_mysql_data:
  lecturer_mysql_data:
