#version: "3.9"
#services:
#  app:
#    build:
#      context: .
#      dockerfile: student-app.dockerfile
#    ports:
#      - "8000:8000"
#      - "5672:5672"

version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: student-app.Dockerfile
    ports:
      - "8000:8000"
    environment:
      RABBITMQ_HOST: rabbitmq
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "15672:15672"
      - "5672:5672"