#version: "3.9"
#services:
#  app:
#    build:
#      context: .
#      dockerfile: student-app.dockerfile
#    ports:
#      - "8000:8000"
#      - "5672:5672"

version: '3.9'
services:
  student-app:
    build:
      context: .
      dockerfile: student-app.Dockerfile
    ports:
      - "8000:8000"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    depends_on:
      - rabbitmq
    networks:
      - my-network
  rabbitmq:
    image: rabbitmq:3.9.9-management-alpine
    hostname: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - "5674:5672"
      - "15672:15672"
    networks:
      - my-network
networks:
  my-network:
    driver: bridge