// Code generated by ent, DO NOT EDIT.

package lecturer

const (
	// Label holds the string label denoting the lecturer type in the database.
	Label = "lecturer"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldFirstName holds the string denoting the first_name field in the database.
	FieldFirstName = "first_name"
	// FieldLastName holds the string denoting the last_name field in the database.
	FieldLastName = "last_name"
	// FieldEmail holds the string denoting the email field in the database.
	FieldEmail = "email"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// EdgeClassLecturers holds the string denoting the class_lecturers edge name in mutations.
	EdgeClassLecturers = "class_lecturers"
	// Table holds the table name of the lecturer in the database.
	Table = "lecturers"
	// ClassLecturersTable is the table that holds the class_lecturers relation/edge.
	ClassLecturersTable = "class_lecturers"
	// ClassLecturersInverseTable is the table name for the ClassLecturer entity.
	// It exists in this package in order to avoid circular dependency with the "classlecturer" package.
	ClassLecturersInverseTable = "class_lecturers"
	// ClassLecturersColumn is the table column denoting the class_lecturers relation/edge.
	ClassLecturersColumn = "lecturer_class_lecturers"
)

// Columns holds all SQL columns for lecturer fields.
var Columns = []string{
	FieldID,
	FieldFirstName,
	FieldLastName,
	FieldEmail,
	FieldDeletedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
