// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"lecturer/ent/classlecturer"
	"lecturer/ent/lecturer"
	"lecturer/ent/predicate"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// LecturerQuery is the builder for querying Lecturer entities.
type LecturerQuery struct {
	config
	ctx                *QueryContext
	order              []OrderFunc
	inters             []Interceptor
	predicates         []predicate.Lecturer
	withClassLecturers *ClassLecturerQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the LecturerQuery builder.
func (lq *LecturerQuery) Where(ps ...predicate.Lecturer) *LecturerQuery {
	lq.predicates = append(lq.predicates, ps...)
	return lq
}

// Limit the number of records to be returned by this query.
func (lq *LecturerQuery) Limit(limit int) *LecturerQuery {
	lq.ctx.Limit = &limit
	return lq
}

// Offset to start from.
func (lq *LecturerQuery) Offset(offset int) *LecturerQuery {
	lq.ctx.Offset = &offset
	return lq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (lq *LecturerQuery) Unique(unique bool) *LecturerQuery {
	lq.ctx.Unique = &unique
	return lq
}

// Order specifies how the records should be ordered.
func (lq *LecturerQuery) Order(o ...OrderFunc) *LecturerQuery {
	lq.order = append(lq.order, o...)
	return lq
}

// QueryClassLecturers chains the current query on the "class_lecturers" edge.
func (lq *LecturerQuery) QueryClassLecturers() *ClassLecturerQuery {
	query := (&ClassLecturerClient{config: lq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := lq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := lq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(lecturer.Table, lecturer.FieldID, selector),
			sqlgraph.To(classlecturer.Table, classlecturer.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, lecturer.ClassLecturersTable, lecturer.ClassLecturersColumn),
		)
		fromU = sqlgraph.SetNeighbors(lq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Lecturer entity from the query.
// Returns a *NotFoundError when no Lecturer was found.
func (lq *LecturerQuery) First(ctx context.Context) (*Lecturer, error) {
	nodes, err := lq.Limit(1).All(setContextOp(ctx, lq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{lecturer.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (lq *LecturerQuery) FirstX(ctx context.Context) *Lecturer {
	node, err := lq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Lecturer ID from the query.
// Returns a *NotFoundError when no Lecturer ID was found.
func (lq *LecturerQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = lq.Limit(1).IDs(setContextOp(ctx, lq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{lecturer.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (lq *LecturerQuery) FirstIDX(ctx context.Context) int {
	id, err := lq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Lecturer entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Lecturer entity is found.
// Returns a *NotFoundError when no Lecturer entities are found.
func (lq *LecturerQuery) Only(ctx context.Context) (*Lecturer, error) {
	nodes, err := lq.Limit(2).All(setContextOp(ctx, lq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{lecturer.Label}
	default:
		return nil, &NotSingularError{lecturer.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (lq *LecturerQuery) OnlyX(ctx context.Context) *Lecturer {
	node, err := lq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Lecturer ID in the query.
// Returns a *NotSingularError when more than one Lecturer ID is found.
// Returns a *NotFoundError when no entities are found.
func (lq *LecturerQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = lq.Limit(2).IDs(setContextOp(ctx, lq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{lecturer.Label}
	default:
		err = &NotSingularError{lecturer.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (lq *LecturerQuery) OnlyIDX(ctx context.Context) int {
	id, err := lq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Lecturers.
func (lq *LecturerQuery) All(ctx context.Context) ([]*Lecturer, error) {
	ctx = setContextOp(ctx, lq.ctx, "All")
	if err := lq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Lecturer, *LecturerQuery]()
	return withInterceptors[[]*Lecturer](ctx, lq, qr, lq.inters)
}

// AllX is like All, but panics if an error occurs.
func (lq *LecturerQuery) AllX(ctx context.Context) []*Lecturer {
	nodes, err := lq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Lecturer IDs.
func (lq *LecturerQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	ctx = setContextOp(ctx, lq.ctx, "IDs")
	if err := lq.Select(lecturer.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (lq *LecturerQuery) IDsX(ctx context.Context) []int {
	ids, err := lq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (lq *LecturerQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, lq.ctx, "Count")
	if err := lq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, lq, querierCount[*LecturerQuery](), lq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (lq *LecturerQuery) CountX(ctx context.Context) int {
	count, err := lq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (lq *LecturerQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, lq.ctx, "Exist")
	switch _, err := lq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (lq *LecturerQuery) ExistX(ctx context.Context) bool {
	exist, err := lq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the LecturerQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (lq *LecturerQuery) Clone() *LecturerQuery {
	if lq == nil {
		return nil
	}
	return &LecturerQuery{
		config:             lq.config,
		ctx:                lq.ctx.Clone(),
		order:              append([]OrderFunc{}, lq.order...),
		inters:             append([]Interceptor{}, lq.inters...),
		predicates:         append([]predicate.Lecturer{}, lq.predicates...),
		withClassLecturers: lq.withClassLecturers.Clone(),
		// clone intermediate query.
		sql:  lq.sql.Clone(),
		path: lq.path,
	}
}

// WithClassLecturers tells the query-builder to eager-load the nodes that are connected to
// the "class_lecturers" edge. The optional arguments are used to configure the query builder of the edge.
func (lq *LecturerQuery) WithClassLecturers(opts ...func(*ClassLecturerQuery)) *LecturerQuery {
	query := (&ClassLecturerClient{config: lq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	lq.withClassLecturers = query
	return lq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		FirstName string `json:"first_name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Lecturer.Query().
//		GroupBy(lecturer.FieldFirstName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (lq *LecturerQuery) GroupBy(field string, fields ...string) *LecturerGroupBy {
	lq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &LecturerGroupBy{build: lq}
	grbuild.flds = &lq.ctx.Fields
	grbuild.label = lecturer.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		FirstName string `json:"first_name,omitempty"`
//	}
//
//	client.Lecturer.Query().
//		Select(lecturer.FieldFirstName).
//		Scan(ctx, &v)
func (lq *LecturerQuery) Select(fields ...string) *LecturerSelect {
	lq.ctx.Fields = append(lq.ctx.Fields, fields...)
	sbuild := &LecturerSelect{LecturerQuery: lq}
	sbuild.label = lecturer.Label
	sbuild.flds, sbuild.scan = &lq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a LecturerSelect configured with the given aggregations.
func (lq *LecturerQuery) Aggregate(fns ...AggregateFunc) *LecturerSelect {
	return lq.Select().Aggregate(fns...)
}

func (lq *LecturerQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range lq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, lq); err != nil {
				return err
			}
		}
	}
	for _, f := range lq.ctx.Fields {
		if !lecturer.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if lq.path != nil {
		prev, err := lq.path(ctx)
		if err != nil {
			return err
		}
		lq.sql = prev
	}
	return nil
}

func (lq *LecturerQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Lecturer, error) {
	var (
		nodes       = []*Lecturer{}
		_spec       = lq.querySpec()
		loadedTypes = [1]bool{
			lq.withClassLecturers != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Lecturer).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Lecturer{config: lq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, lq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := lq.withClassLecturers; query != nil {
		if err := lq.loadClassLecturers(ctx, query, nodes,
			func(n *Lecturer) { n.Edges.ClassLecturers = []*ClassLecturer{} },
			func(n *Lecturer, e *ClassLecturer) { n.Edges.ClassLecturers = append(n.Edges.ClassLecturers, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (lq *LecturerQuery) loadClassLecturers(ctx context.Context, query *ClassLecturerQuery, nodes []*Lecturer, init func(*Lecturer), assign func(*Lecturer, *ClassLecturer)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Lecturer)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.ClassLecturer(func(s *sql.Selector) {
		s.Where(sql.InValues(lecturer.ClassLecturersColumn, fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.lecturer_class_lecturers
		if fk == nil {
			return fmt.Errorf(`foreign-key "lecturer_class_lecturers" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "lecturer_class_lecturers" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (lq *LecturerQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := lq.querySpec()
	_spec.Node.Columns = lq.ctx.Fields
	if len(lq.ctx.Fields) > 0 {
		_spec.Unique = lq.ctx.Unique != nil && *lq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, lq.driver, _spec)
}

func (lq *LecturerQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   lecturer.Table,
			Columns: lecturer.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: lecturer.FieldID,
			},
		},
		From:   lq.sql,
		Unique: true,
	}
	if unique := lq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := lq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, lecturer.FieldID)
		for i := range fields {
			if fields[i] != lecturer.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := lq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := lq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := lq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := lq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (lq *LecturerQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(lq.driver.Dialect())
	t1 := builder.Table(lecturer.Table)
	columns := lq.ctx.Fields
	if len(columns) == 0 {
		columns = lecturer.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if lq.sql != nil {
		selector = lq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if lq.ctx.Unique != nil && *lq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range lq.predicates {
		p(selector)
	}
	for _, p := range lq.order {
		p(selector)
	}
	if offset := lq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := lq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// LecturerGroupBy is the group-by builder for Lecturer entities.
type LecturerGroupBy struct {
	selector
	build *LecturerQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (lgb *LecturerGroupBy) Aggregate(fns ...AggregateFunc) *LecturerGroupBy {
	lgb.fns = append(lgb.fns, fns...)
	return lgb
}

// Scan applies the selector query and scans the result into the given value.
func (lgb *LecturerGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, lgb.build.ctx, "GroupBy")
	if err := lgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*LecturerQuery, *LecturerGroupBy](ctx, lgb.build, lgb, lgb.build.inters, v)
}

func (lgb *LecturerGroupBy) sqlScan(ctx context.Context, root *LecturerQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(lgb.fns))
	for _, fn := range lgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*lgb.flds)+len(lgb.fns))
		for _, f := range *lgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*lgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := lgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// LecturerSelect is the builder for selecting fields of Lecturer entities.
type LecturerSelect struct {
	*LecturerQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ls *LecturerSelect) Aggregate(fns ...AggregateFunc) *LecturerSelect {
	ls.fns = append(ls.fns, fns...)
	return ls
}

// Scan applies the selector query and scans the result into the given value.
func (ls *LecturerSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ls.ctx, "Select")
	if err := ls.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*LecturerQuery, *LecturerSelect](ctx, ls.LecturerQuery, ls, ls.inters, v)
}

func (ls *LecturerSelect) sqlScan(ctx context.Context, root *LecturerQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ls.fns))
	for _, fn := range ls.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ls.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ls.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
